pipeline:  

  publish:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: ${DOCKER_EMAIL}
    repo: lobre/wordpress-ci
    tags:
      - latest
    dockerfile: ./Dockerfile
