version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    container_name: wordpress_db
    networks:
      - wordpress
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: wordpress_php
    networks:
      - wordpress
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
    volumes:
      - ./src:/var/www/html

  apache:
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    container_name: wordpress_apache
    networks:
      - wordpress
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html
    volumes:
      - ./src:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.home=true
      - traefik.port=80
      - traefik.frontend.rule=Host:wordpress.localtest.me

  mailhog:
    image: mailhog/mailhog
    container_name: wordpress_mailhog
    networks:
      - wordpress
    labels:
      - traefik.enable=true
      - traefik.home=true
      - traefik.port=8025
      - traefik.frontend.rule=Host:mailhog-wordpress.localtest.me

networks:
  wordpress: